name = "meridaunclick"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "generico_db"
database_id = "38dd85ba-03dc-4937-af19-4d1c41a18f27"

[[r2_buckets]]
binding = "R2"
bucket_name = "my-emdash-media"

[vars]
R2_FOLDER = "aunclick"
